import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :react_vite, ReactViteWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "46U67KrCF52zO+lTRnXslp4AB7oYncC+3CHj33vxjyanYqD5Is2xBwZANrlaDSGg",
  # In development, assets are served by the Vite dev server, so `static_url/2`
  # (used by the asset tags in root.html.heex) points at it instead of Phoenix.
  static_url: [host: "localhost", port: 5173],
  # Run the Vite dev server alongside Phoenix. PhoenixVite.Npm.run/2 shells out
  # to `npm exec -- vite ...` (the `:vite` profile in config/config.exs). The
  # `ssr` watcher rebuilds priv/ssr/ssr.cjs on change; because it's CommonJS the
  # Inertia.SSR Node pool reloads it without a restart in development.
  watchers: [
    vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]},
    ssr: {PhoenixVite.Npm, :run, [:vite, ~w(build --ssr js/ssr.jsx --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :react_vite, ReactViteWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Assets are reloaded by the Vite dev server, so phoenix_live_reload only
      # watches server-side files here (no priv/static asset pattern).
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/react_vite_web/router\.ex$"E,
      ~r"lib/react_vite_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :react_vite, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
